name: Python Linting Workflow

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9]  # Specify your desired Python version

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Update to the latest compatible version

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Update to the latest compatible version
      with:
        node-version: 16  # Specify Node.js version 16

    - name: Set up Python
      uses: actions/setup-python@v2  # Update to the latest compatible version
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        # Install the 'flake8' linter
        pip install flake8

    - name: Run Flake8 on src/
      run: |
        # Run 'flake8' on the code in the 'src/' folder
        flake8 src/  # Replace with your linter command and configuration options

    - name: Run Flake8 on tests/
      run: |
        # Run 'flake8' on the tests in the 'tests/' folder
        flake8 tests/  # Replace with your linter command and configuration options

